---
title: 07.使用Typescript重构Axios--处理异常（七）
date: 2022-05-30 14:38:14
permalink: /pages/eb9863/
categories:
  - 源码
  - Axios
tags:
  - Typescript
  - Axios
author:
  name: 旗木五五开
  link: https://github.com/2513022260
---

# 使用 Typescript 重构 Axios--处理异常（七）

我们之前的接口都是正常情况下的输出，接下来我们通过`reject`处理异常：

<!-- more -->

## 快速跳转

- 使用 Typescript 重构 Axios [链接](/pages/1fda4a/)
- 使用 Typescript 重构 Axios--实现基础（一） [链接](/pages/7feef0/)
- 使用 Typescript 重构 Axios--处理 GET 请求的 URL 参数（二） [链接](/pages/518c20/)
- 使用 Typescript 重构 Axios--处理 POST 请求参数（三） [链接](/pages/a667c9/)
- 使用 Typescript 重构 Axios--处理请求头 header（四） [链接](/pages/52e3b8/)
- 使用 Typescript 重构 Axios--处理响应数据（五） [链接](/pages/5e813a/)
- 使用 Typescript 重构 Axios--处理响应 header 和 data（六） [链接](/pages/d9c670/)
- 使用 Typescript 重构 Axios--处理异常（七） [链接](/pages/eb9863/)

## 需求分析

常见的请求异常有：

- 网络异常
- 请求超时
- 状态码不在 200-300 之间的

## 异常处理

### 网络异常

当网络出现异常的时候发送请求会触发 `XMLHttpRequest` 对象实例的 `onerror` 事件，于是我们就可以在 `onerror` 的事件回调函数中捕获此类错误。在`xhr.ts`文件下添加`onerror`事件，放到`xhr.send(data)`后面：

```ts
...
// 5 处理异常
// 5.1 网络错误事件
xhr.onerror = function() {
  reject(new Error('Net Error'))
}
```

### 请求超时

请求超出某个时间还未收到响应，则自动终止请求，并触发 `XMLHttpRequest` 对象实例的 `ontimeout` 事件：

1. 首先，允许用户配置超时时间，我们给请求参数接口类型 `AxiosRequestConfig` 里添加 `timeout`。

```ts
// /src/axios/types/index.ts
export interface AxiosRequestConfig {
  url: string
  method?: string
  headers?: any
  data?: any
  params?: any
  responseType?: XMLHttpRequestResponseType
  timeout?: number
}
```

2. 然后在 `xhr.ts` 下增加参数配置：

```ts
// /src/axios/xhr.ts
const {
  url,
  method = 'get',
  data = null,
  headers,
  responseType,
  timeout
} = config

// 有 timeout 配置到 xhr.timeout
if (timeout) {
  xhr.timeout = timeout
}
```

3. 最后添加`XMLHttpRequest`对象实例的 `ontimeout` 事件

```ts
// 5.2 超时 timeout
xhr.ontimeout = function () {
  reject(new Error(`Timeout of ${timeout} ms exceeded`))
}
```

### 状态码不在 200-300 之间的

正常的一个请求往往会返回 `200-300` 之间的 `HTTP` 状态码，对于不在这个区间的状态码，我们也把它们认为是一种错误的情况做处理。

1. 首先，我们先在 `xhr` 函数中的 `onreadystatechange` 的回调函数中，添加了对 `request.status` 的判断，因为当出现网络错误或者超时错误的时候，该值都为 `0`。

```ts
// 5.3 网络错误或者超时错误
if (xhr.status === 0) return
```

2. 然后，判断状态码是否在 200-300 之间。

```ts
// 5.4 状态码判断
handleResponse(response)
function handleResponse(response: AxiosResponse): void {
  if (response.status >= 200 && response.status < 300) {
    resolve(response)
  } else {
    reject(new Error(`Request failed with status code ${response.status}`))
  }
}
```

## DEMO

创建`/src/views/ExceptionView.vue`文件：

### vue 示例

```vue
<template>
  <div class="home">
    <button @click="clickGetMethod">正常请求</button>
    <button @click="clickUrlError">url错误</button>
    <button @click="clickNetError">网络错误</button>
    <button @click="clickTimeoutError">请求超时</button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import axios from '@/axios/index'

export default defineComponent({
  setup() {
    const clickGetMethod = () => {
      axios({
        method: 'get',
        url: '/api/base/get'
      })
        .then(res => {
          console.log(res)
        })
        .catch(e => {
          console.log('e', e)
        })
    }
    const clickUrlError = () => {
      axios({
        method: 'get',
        url: '/api/base/get123'
      })
        .then(res => {
          console.log(res)
        })
        .catch(e => {
          console.log('url error', e)
        })
    }
    const clickNetError = () => {
      setTimeout(() => {
        axios({
          method: 'get',
          url: '/api/base/get'
        })
          .then(res => {
            console.log(res)
          })
          .catch(e => {
            console.log('net error', e)
          })
      }, 5000)
    }
    const clickTimeoutError = () => {
      axios({
        method: 'get',
        url: '/api/base/get',
        timeout: 2000
      })
        .then(res => {
          console.log(res)
        })
        .catch(e => {
          console.log('timeout error', e)
        })
    }
    return {
      clickGetMethod,
      clickUrlError,
      clickNetError,
      clickTimeoutError
    }
  }
})
</script>

<style lang="stylus" scoped></style>
```

### 测试结果：

点击 url 错误：
![结果](/blog/img/source/axios-17.png)
点击网络错误：
![结果](/blog/img/source/axios-18.png)
点击请求超时：
![结果](/blog/img/source/axios-19.png)
